[programs.localnet]
sol_nft_staking = "D42AsUF2UbUcyBtK2Jvbym2ALfksvgeScNNtMg7KrSfj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./test-keypair.json"

[test]
# Clone the metadata program and the executable account associated with it
# for use in integration tests
clone = [
  {address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"}, 
  {address = "PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT"}
]
validator = {url = "mainnet-beta"}

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
